name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, macos-11, ubuntu-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: seanmiddleditch/gha-setup-ninja@856654e80dd21909aec244cd01bb96e5c841d64f
      - name: ninja check
        run: ninja --version
